(function($,h,c){var a=$([]),e=$.resize=$.extend($.resize,{}),i,k="setTimeout",j="resize",d=j+"-special-event",b="delay",f="throttleWindow";e[b]=250;e[f]=true;$.event.special[j]={setup:function(){if(!e[f]&&this[k]){return false}var l=$(this);a=a.add(l);$.data(this,d,{w:l.width(),h:l.height()});if(a.length===1){g()}},teardown:function(){if(!e[f]&&this[k]){return false}var l=$(this);a=a.not(l);l.removeData(d);if(!a.length){clearTimeout(i)}},add:function(l){if(!e[f]&&this[k]){return false}var n;function m(s,o,p){var q=$(this),r=$.data(this,d);r.w=o!==c?o:q.width();r.h=p!==c?p:q.height();n.apply(this,arguments)}if($.isFunction(l)){n=l;return m}else{n=l.handler;l.handler=m}}};function g(){i=h[k](function(){a.each(function(){var n=$(this),m=n.width(),l=n.height(),o=$.data(this,d);if(m!==o.w||l!==o.h){n.trigger(j,[o.w=m,o.h=l])}});g()},e[b])}})(jQuery,this);function tm_sticky(){if(jQuery('.masthead-header-stickyOnScroll').length>0){var pageWidth=jQuery(window).width();var selector=jQuery('.masthead-header-stickyOnScroll');var selectorParent='stickable-header-sticky-wrapper';if(jQuery('body').hasClass('thememount-header-style-3')||jQuery('body').hasClass('thememount-header-style-6')){selector=jQuery('#navbar');selectorParent='navbar-sticky-wrapper';}
if(parseInt(pageWidth)>parseInt(tm_breakpoint)){if(jQuery(selector).parent().attr('id')!=selectorParent){jQuery(selector).sticky({topSpacing:0});}else{}}else{if(jQuery(selector).parent().attr('id')==selectorParent){jQuery(selector).unstick();}else{}}}}
function thememount_setCookie(c_name,value,exdays){var now=new Date();var time=now.getTime();time+=(3600*1000)*24;now.setTime(time);var c_value=escape(value)+((exdays==null)?"":"; expires="+now.toGMTString());document.cookie=c_name+"="+c_value;}
function setHeight(column){var maxHeight=0;column=jQuery(column);column.css('height','auto');if(jQuery(window).width()>479){column.each(function(){if(jQuery(this).height()>maxHeight){maxHeight=jQuery(this).height();}});column.height(maxHeight);}}
function thememount_blogmasonry(){if(jQuery().isotope){if(jQuery('#content.thememount-blog-col-page').length>0){jQuery('#content.thememount-blog-col-page').masonry();jQuery('#content.thememount-blog-col-page').isotope({itemSelector:'.post-box',masonry:{},sortBy:'original-order'});}}}
function thememount_stickyFooter(){if(jQuery('body').hasClass('thememount-sticky-footer')&&jQuery('body').hasClass('thememount-wide')){jQuery('div#main').css('marginBottom',jQuery('footer#colophon').height());}}
function setEmptySelectBox(element){if(jQuery(element).val()==""){jQuery(element).addClass("empty");}else{jQuery(element).removeClass("empty");}}
function tm_hide_togle_link(){if(jQuery('#navbar div.mega-menu-wrap ul.mega-menu').length>0){jQuery('h3.menu-toggle').css('display','none');}}
function thememount_reset_gmap(){jQuery('.thememount-fbar-box-w > div > aside').each(function(){var mainthis=jQuery(this);jQuery('iframe[src^="https://www.google.com/maps/"], iframe[src^="http://www.google.com/maps/"]',mainthis).each(function(){if(!jQuery(this).hasClass('thememount-set-gmap')){jQuery(this).attr('src',jQuery(this).attr('src')+'');jQuery(this).load(function(){jQuery(this).addClass('thememount-set-gmap').animate({opacity:1},1000);});}})});}
function thememount_hide_gmap(){jQuery('.thememount-fbar-box-w > div > aside').each(function(){var mainthis=jQuery(this);jQuery('iframe[src^="https://www.google.com/maps/"], iframe[src^="http://www.google.com/maps/"]',mainthis).each(function(){if(!jQuery(this).hasClass('thememount-set-gmap')){jQuery(this).css({opacity:0});jQuery(this).css('display','block');}})});}
function isotope(){var gallery_item=jQuery('.portfolio-wrapper');var filterLinks=jQuery('.portfolio-sortable-list a');if(gallery_item.parents('.thememount-pf-ajax-sorting-yes').length==0){gallery_item.isotope({animationEngine:'best-available'})
filterLinks.click(function(e){var selector=jQuery(this).attr('data-filter');gallery_item.isotope({filter:selector,itemSelector:'.isotope-item'});filterLinks.removeClass('selected');jQuery('#filter-by li').removeClass('current-cat');jQuery(this).addClass('selected');e.preventDefault();});}};jQuery(document).ready(function($){"use strict";if(jQuery('body').hasClass('thememount-one-page-site')){var sections=jQuery('.wpb_row, #tm-header-slider'),nav=jQuery('.mega-menu-wrap, .menu-main-menu-container'),nav_height=jQuery('#site-navigation').data('sticky-height');jQuery(window).on('scroll',function(){if(typeof jQuery(this)!='undefined'){var cur_pos=jQuery(this).scrollTop();sections.each(function(){var top=jQuery(this).offset().top-nav_height,bottom=top+jQuery(this).outerHeight();if(cur_pos>=top&&cur_pos<=bottom){if(typeof jQuery(this)!='undefined'&&typeof jQuery(this).attr('id')!='undefined'&&jQuery(this).attr('id')!=''){var mainThis=jQuery(this);nav.find('a').removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');jQuery(this).addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');var arr=mainThis.attr('id');jQuery('#navbar a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a').each(function(){var menuAttr=jQuery(this).attr('href').split('#')[1];if(menuAttr==arr){jQuery(this).parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');}})}}});}});nav.find('a').on('click',function(){var $el=jQuery(this),id=$el.attr('href');var arr=id.split('#')[1];jQuery('html, body').animate({scrollTop:jQuery('#'+arr).offset().top-nav_height},500);return false;});}
if(jQuery("div.search_field.by_treatment select").length>0){setEmptySelectBox(jQuery("div.search_field.by_treatment select"));jQuery("div.search_field.by_treatment select").change(function(){setEmptySelectBox(jQuery(this));});}
var teamSearchBoxIconOpen='tmicon-'+jQuery('.thememount-fbar-btn > a').data('openicon');var teamSearchBoxIconClosed='tmicon-'+jQuery('.thememount-fbar-btn > a').data('closeicon');thememount_hide_gmap();jQuery(".thememount-fbar-btn a").click(function(){if(jQuery(".thememount-fbar-box-w").css('display')=='none'){jQuery('.thememount-fbar-btn i').removeClass(teamSearchBoxIconOpen).addClass(teamSearchBoxIconClosed);jQuery(".thememount-fbar-box-w").slideDown('400',function(){thememount_reset_gmap();jQuery(".thememount-set-gmap").fadeIn(1000);});}else{jQuery('.thememount-fbar-btn i').removeClass(teamSearchBoxIconClosed).addClass(teamSearchBoxIconOpen);jQuery(".thememount-set-gmap").hide();jQuery(".thememount-fbar-box-w").slideUp();}
return false;});jQuery('#site-navigation .menu-main-menu-container > ul > li:has(ul), #site-navigation .mega-menu-wrap > ul > li:has(ul)').append("<span class='righticon'><i class='tmicon-fa-plus-square'></i></span>");jQuery('#site-navigation .menu-main-menu-container > ul > li.menu-item-language, #site-navigation .mega-menu-wrap > ul > li.menu-item-language').addClass("mega-menu-item mega-menu-item-type-custom mega-menu-item-object-custom mega-menu-item-has-children mega-menu-item-13 mega-align-bottom-left mega-menu-flyout");jQuery('#site-navigation .mega-menu-wrap > ul > li.menu-item-language').addClass("mega-menu-item mega-menu-item-type-custom mega-menu-item-object-custom mega-menu-item-has-children mega-menu-item-13 mega-align-bottom-left mega-menu-flyout");jQuery('#site-navigation .mega-menu-wrap > ul > li.menu-item-language ul').addClass("mega-sub-menu");jQuery('#navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.menu-item-language > a').show();jQuery('#site-navigation .mega-menu-wrap > ul > li.menu-item-language').hover(function(){jQuery('#navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal .mega-menu-flyout .mega-sub-menu').css("display","none");jQuery(this).find('ul').show();},function(){jQuery(this).find('ul').hide();});jQuery('.menu li.current-menu-item').parents('li.mega-menu-megamenu').addClass('mega-current-menu-ancestor');if(!jQuery('body').hasClass("tm-header-invert")){jQuery(".nav-menu > li:eq(-2), #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.mega-menu-item:eq(-2)").addClass("lastsecond");jQuery(".nav-menu > li:eq(-1), #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.mega-menu-item:eq(-1)").addClass("last");}
jQuery(".thememount-row-fullwidth-true.full-colum-height-widht > .grid_section > .vc_column_container img.vc_single_image-img").each(function(){var imgsrc=jQuery(this).attr("src");jQuery(this).parent().parent().parent().parent().parent('.vc_column_container').css('background-image','url('+imgsrc+')');});jQuery(".search_box a").click(function(){jQuery(".thememount-header-style-3 #stickable-header .headerlogo, body.thememount-header-style-3 header .thememount-topbar").css('z-index','9');jQuery(".tm-header-overlay .thememount-fbar-btn").css('z-index','9');jQuery(".thememount-fbar-btn").css('z-index','9');jQuery(".site-header, .headerblock").css('z-index','1000000');jQuery(".header-controls").css('z-index','1000000');jQuery(".k_flying_searchform_wrapper #flying_searchform").fadeIn(400,function(){jQuery(".field.searchform-s").focus();});return false;});jQuery(".w-search-close").click(function(){jQuery(".k_flying_searchform_wrapper #flying_searchform").fadeOut(400,function(){jQuery("body.thememount-header-style-3 header .thememount-topbar, .site-header, .headerblock, .header-controls, .thememount-header-style-3 #stickable-header .headerlogo, .tm-header-overlay .thememount-fbar-btn, .thememount-fbar-btn").removeAttr("style");});return false;});if(typeof jQuery.fn.prettyPhoto=="function"){jQuery('div.gallery a[href*=".jpg"], div.gallery a[href*=".jpeg"], div.gallery a[href*=".png"], div.gallery a[href*=".gif"]').each(function(){if(jQuery(this).attr('target')!='_blank'){jQuery(this).removeAttr("data-rel").attr('rel','prettyPhoto[wp-gallery]');}});jQuery("a[data-rel^='prettyPhoto']").prettyPhoto();jQuery("a[rel^='prettyPhoto']").prettyPhoto();jQuery('.gallery-item .gallery-icon a[href*=".jpg"], .gallery-item .gallery-icon a[href*=".jpeg"], .gallery-item .gallery-icon a[href*=".png"], .gallery-item .gallery-icon a[href*=".gif"]').prettyPhoto();}
$("[data-appear-animation]").each(function(){var self=$(this);var animation=self.data("appear-animation");var delay=(self.data("appear-animation-delay")?self.data("appear-animation-delay"):0);if($(window).width()>959){self.html('0');self.waypoint(function(direction){if(!self.hasClass('completed')){var from=self.data('from');var to=self.data('to');var interval=self.data('interval');self.numinate({format:'%counter%',from:from,to:to,runningInterval:2000,stepUnit:interval,onComplete:function(elem){self.addClass('completed');}});}},{offset:'85%'});}else{if(animation=='animateWidth'){self.css('width',self.data("width"));}}});jQuery(window).scroll(function(){tm_scroll_to_top();});jQuery(window).resize(function(){tm_scroll_to_top();});jQuery(window).load(function(){tm_scroll_to_top();});var offset=85;var duration=500;jQuery("#totop").click(function(event){event.preventDefault();jQuery("html, body").animate({scrollTop:0},duration);return false;})
function tm_scroll_to_top(){if(jQuery(window).scrollTop()>offset){jQuery("#totop").fadeIn(duration);}else{jQuery("#totop").fadeOut(duration);}}
if(jQuery('.thememount-testimonial-box').length>0){setHeight('.thememount-testimonial-box.col-lg-6.col-sm-6.col-md-6');setHeight('.thememount-testimonial-box.col-lg-4.col-sm-6.col-md-4');setHeight('.thememount-testimonial-box.col-lg-3.col-sm-6.col-md-3');}
if(jQuery('.masthead-header-stickyOnScroll').length>0){tm_sticky();}
$('#site-navigation a[href="#"]').click(function(){return false;});$('.thememount-team-social-links li a').tooltip({'placement':'top'});$('.site-header .social-icons li a').tooltip({'placement':'bottom'});$('.site-footer .social-icons li a').tooltip({'placement':'bottom'});$('.thememount-pf-navbar-wrapper a').tooltip({'placement':'top'});$('.thememount-clients a').tooltip({'placement':'top'});$(".thememount-close-icon").click(function(){$("#page").css('padding-top',(parseInt($("#page").css('padding-top'))-parseInt($(".thememount-wbar").height()))+'px');$(".thememount-wbar").slideUp();thememount_setCookie('kw_hidewbar','1',1);});var galleryHTML=jQuery(".gallery-size-full br").each(function(){jQuery(this).remove();});jQuery("a.thememount-open-gallery").click(function(){var href=jQuery(this).attr('href');var id=href.replace("#thememount-embed-code-","");var currid=window['api_images_'+id];jQuery.prettyPhoto.open(window['api_images_'+id],window['api_titles_'+id],window['api_desc_'+id]);});if(jQuery('.thememount-effect-carousel').length>0){jQuery('.thememount-effect-carousel').each(function(){var itemsColumns2={0:{items:1},479:{items:2},768:{items:2},1200:{items:3}};if(jQuery(this).hasClass('thememount-carousel-col-one')){itemsColumns2={0:{items:1},479:{items:1},768:{items:1},1200:{items:1}};}else if(jQuery(this).hasClass('thememount-carousel-col-two')){itemsColumns2={0:{items:1},479:{items:2},768:{items:2},1200:{items:2}};}else if(jQuery(this).hasClass('thememount-carousel-col-four')){itemsColumns2={0:{items:1},479:{items:2},768:{items:2},1200:{items:4}};}else if(jQuery(this).hasClass('thememount-carousel-col-five')){itemsColumns2={0:{items:1},479:{items:2},768:{items:3},1200:{items:5}};}else if(jQuery(this).hasClass('thememount-carousel-col-six')){itemsColumns2={0:{items:1},479:{items:2},768:{items:3},1200:{items:6}};}
var owlWrap=jQuery(this);var paginationOption=false;if(jQuery(this).hasClass('thememount-with-pagination')){paginationOption=true;}
if(owlWrap.length>0){if(jQuery().owlCarousel){owlWrap.each(function(){var carousel=$(this).find('.thememount-carousel-items-wrapper'),navigation=$(this).find('.thememount-carousel-controls-inner'),nextBtn=navigation.find('a.thememount-carousel-next'),prevBtn=navigation.find('a.thememount-carousel-prev');var rtloption=false;if(jQuery('body').hasClass('rtl')){rtloption=true;}
var val_autoplay=true;var val_autoplaySpeed=800;var val_loop=false;var val_autoplayTimeout=4500;var val_animatein=false;var val_animateout=false;if(owlWrap.data('autoplayspeed')!=''){val_autoplaySpeed=jQuery.trim(owlWrap.data('autoplayspeed'));}
if(owlWrap.data('autoplay')=='0'){val_autoplay=false;val_autoplaySpeed=false;}
if(owlWrap.data('loop')=='1'){val_loop=true;}
if(owlWrap.data('autoplaytimeout')!=''){val_autoplayTimeout=jQuery.trim(owlWrap.data('autoplaytimeout'));}
if(owlWrap.data('animatein')!=''){val_animatein=jQuery.trim(owlWrap.data('animatein'));}
if(owlWrap.data('animateout')!=''){val_animateout=jQuery.trim(owlWrap.data('animateout'));}
carousel.owlCarousel({autoplay:val_autoplay,autoplayTimeout:val_autoplayTimeout,autoplaySpeed:val_autoplaySpeed,navSpeed:val_autoplaySpeed,dots:paginationOption,dotsSpeed:val_autoplaySpeed,rtl:rtloption,loop:val_loop,margin:30,nav:false,responsive:itemsColumns2,});nextBtn.click(function(){carousel.trigger('next.owl.carousel',[val_autoplaySpeed]);return false;});prevBtn.click(function(){carousel.trigger('prev.owl.carousel',[val_autoplaySpeed]);return false;});if(val_loop==false){carousel.on('changed.owl.carousel',function(event){var newindex=event.item.index+event.page.size;if(newindex==event.item.count){var totalTimeout=parseInt(val_autoplayTimeout)+parseInt(val_autoplayTimeout);setTimeout(function(){carousel.trigger('to.owl.carousel',[0,val_autoplaySpeed,val_autoplaySpeed]);},totalTimeout);}});}});};};});}
var gallery_item=$('.portfolio-wrapper'),filterLinks=$('.portfolio-sortable-list a');if(jQuery().isotope){$(window).load(function(){isotope();thememount_blogmasonry();});$(window).resize(function(){isotope();});}
$('.thememount-portfolio-likes').live('click',function(e){e.preventDefault();var link=$(this);if(link.hasClass('like-active'))return false;$(this).html('<i class="tmicon-fa-circle-o-notch tmicon-fa-spin"></i>');var id=$(this).attr('id');$.post(ajaxurl,{action:'thememount-portfolio-likes',likes_id:id},function(data){$('i.tmicon-fa-heart-o',link).removeClass('tmicon-fa-heart-o').addClass('tmicon-fa-heart');link.html(data).addClass('like-active');});});jQuery('footer#colophon').resize(function(){thememount_stickyFooter();});thememount_stickyFooter();jQuery("#tm-header-slider > div > div:contains('Revolution Slider Error')").css("margin","auto");if(jQuery('.thememount-pf-ajax-sorting-yes').length>0){jQuery('.thememount-pf-ajax-sorting-yes').each(function(){var TMajaxSorting=jQuery(this);var TMajaxSortingContainer=jQuery('.thememount-items-wrapper',this);var orderby_list=['none','ID','author','title','name','date','modified','rand','comment_count'];var order_list=['ASC','DESC'];var orderby=jQuery(this).data('orderby');var order=jQuery(this).data('order');if(jQuery.inArray(orderby,orderby_list)==-1){orderby='date';}
if(jQuery.inArray(order,order_list)==-1){order='DESC';}
jQuery("nav.portfolio-sortable-list ul li a",TMajaxSorting).click(function(){if(!jQuery(this).hasClass('tm-sorting-clicked')&&!jQuery(this).hasClass('selected')){jQuery("nav.portfolio-sortable-list ul li a",TMajaxSorting).addClass('tm-sorting-clicked');jQuery(".thememount-items-wrapper",TMajaxSorting).append('<div class="tm-pf-ajax-loading-boxes"></div>');var loadingIcon='<i class="tmicon-fa-circle-o-notch tmicon-fa-spin" style="width:1px;"></i>';var thisAtag=jQuery(this);var show=jQuery(TMajaxSorting).data('show');var column=jQuery(TMajaxSorting).data('column');var pagination=jQuery(TMajaxSorting).data('pagination');var category=jQuery(thisAtag).data('filter');var orderby=jQuery(TMajaxSorting).data('orderby');var order=jQuery(TMajaxSorting).data('order');var paged=jQuery(TMajaxSorting).data('paged');var sortable=jQuery(TMajaxSorting).data('sortable');var catorderby=jQuery(TMajaxSorting).data('catorderby');var catorder=jQuery(TMajaxSorting).data('catorder');console.log(catorderby);var originalText=jQuery(thisAtag).html();jQuery(thisAtag).html(loadingIcon+' '+originalText);var data={"action":"thememount_pf_sorting",'show':show,'column':column,'pagination':pagination,'category':category,'orderby':orderby,'order':order,'paged':paged,'sortable':sortable,'catorderby':catorderby,'catorder':catorder,};jQuery.post(ajaxurl,data,function(response){jQuery(TMajaxSortingContainer).html(response);jQuery("nav.portfolio-sortable-list ul li a",TMajaxSorting).removeClass('tm-sorting-clicked selected');jQuery(thisAtag).addClass('selected');jQuery(thisAtag).html(originalText);});}
return false;});});}});jQuery(window).load(function(){"use strict";jQuery('#pageoverlay').fadeOut(500);var $container=jQuery('.portfolio-wrapper');if($container.parents('.thememount-pf-ajax-sorting-yes').length==0){$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:false,}});jQuery('nav.portfolio-sortable-list ul li a').click(function(){var selector=jQuery(this).attr('data-filter');$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:false,}});jQuery('nav.portfolio-sortable-list').find('a.selected').removeClass('selected');jQuery(this).addClass('selected');return false;});}
if(jQuery('.thememount-slider-wrapper .flexslider').length>0){jQuery('.thememount-slider-wrapper .flexslider').flexslider({animation:"slide",controlNav:false,directionNav:true,start:function(){thememount_blogmasonry();}});}
(function(){var nav=jQuery('#site-navigation'),button,menu;if(!nav)
return;button=nav.find('.menu-toggle');if(!button)
return;menu=nav.find('.nav-menu');if(!menu||!menu.children().length){button.hide();return;}
jQuery('.menu-toggle').on('click.howes',function(){nav.toggleClass('toggled-on');});})();jQuery('.righticon').click(function(){if(jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').hasClass('open')){jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').removeClass('open');jQuery('i',jQuery(this)).removeClass('tmicon-fa-minus-square').addClass('tmicon-fa-plus-square');}else{jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').addClass('open');jQuery('i',jQuery(this)).removeClass('fa-plus-square').addClass('tmicon-fa-minus-square');}
return false;});jQuery('.righticon').each(function(){var mainele=this;if(jQuery(mainele).prev().prev().length>0){if(jQuery(mainele).prev().prev().attr('href')=='#'){jQuery(mainele).prev().prev().click(function(){jQuery(mainele).trigger("click");});}}});thememount_blogmasonry();});jQuery(window).resize(function(){if(jQuery('.thememount-testimonial-box').length>0){setHeight('.thememount-testimonial-box.col-lg-4.col-sm-6.col-md-4');setHeight('.thememount-testimonial-box.col-lg-6.col-sm-6.col-md-6');setHeight('.thememount-testimonial-box.col-lg-3.col-sm-6.col-md-3');}
tm_sticky();});